import turtle
import bioInfo

# print(bioInfo.traduire("AUCGCGAUAGCGCUAGCUGAUCGAUCGGCUAGCUAUCGCGAUAGCGCUAGCUGAUCGAUCGGCUAGCUAUCGCGAUAGCGCUAGCUGAUCGAUCGGCUAGCUAUCGCGAUAGCGCUAGCUGAUCGAUCGGCUAGCU"))

for i in range(20):
    bioInfo.carre(20,i)

turtle.mainloop()